#!/usr/bin/env python3
"""Compile AI artwork to the panel's exact 2-bit pigment palette, without dithering."""
from pathlib import Path
from PIL import Image
root=Path(__file__).resolve().parents[1]
w,h=704,420
palette=[(0,0,0),(255,255,255),(255,213,0),(200,25,32)]
im=Image.open(root/'assets/sleep-squirrel-source.png').convert('RGB').resize((w,h),Image.Resampling.LANCZOS)
codes=[min(range(4),key=lambda c:sum((rgb[i]-palette[c][i])**2 for i in range(3))) for rgb in im.getdata()]
packed=bytes(sum(codes[j+k]<<(6-2*k) for k in range(4)) for j in range(0,len(codes),4))
scene=root/'ESP32S3_Dashboard'
(scene/'SleepArtwork.h').write_text('#pragma once\n#include <stdint.h>\nconstexpr int SLEEP_ART_WIDTH=704,SLEEP_ART_HEIGHT=420;\nextern const uint8_t sleepArtwork[SLEEP_ART_WIDTH*SLEEP_ART_HEIGHT/4];\n')
rows=[','.join('0x%02x'%b for b in packed[i:i+24]) for i in range(0,len(packed),24)]
(scene/'SleepArtwork.cpp').write_text('// Generated by tools/generate_sleep_asset.py from AI-generated artwork.\n#include "SleepArtwork.h"\nconst uint8_t sleepArtwork[SLEEP_ART_WIDTH*SLEEP_ART_HEIGHT/4]={\n'+',\n'.join(rows)+'\n};\n')
preview=Image.new('RGB',(w,h));preview.putdata([palette[c] for c in codes]);preview.save(root/'docs/images/sleep-artwork-native.png')
print('Packed sleep artwork:',len(packed),'bytes')
